# This is a basic workflow to help you get started with Actions

name: Deploy Website

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploying to surge
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with: 
          node-version: 12
      - name: Prepare For yarn installation 
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - name: Install Yarn
        run: sudo apt update && sudo apt install yarn
      - name: Build React App
        run: yarn build
      - name: Install Surge 
        run: npm install -g surge
      - name: Run Surge 
        run: surge ./build zaheer-covid-19-tracker-using-react.surge.sh --token ${{secrets.SURGE_TOKEN}}
